use_frameworks!

platform :ios, '8.0'

target 'LCEasyTableView_Example' do
  pod 'LCEasyTableView', :path => '../'

  pod 'YYKit'

  target 'LCEasyTableView_Tests' do
    inherit! :search_paths

    
  end
end
