use_frameworks!

platform :ios, '8.0'

target 'LCTableView_Example' do
  pod 'LCTableView', :path => '../'

  pod 'YYKit'
  
  target 'LCTableView_Tests' do
    inherit! :search_paths

    
  end
end
